export const schema = [
	'PRAGMA foreign_keys = ON;',
	`CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		google_id TEXT,
		email TEXT NOT NULL UNIQUE,
		display_name TEXT NOT NULL,
		photo_url TEXT,
		role TEXT NOT NULL CHECK (role IN ('user', 'admin')),
		status TEXT NOT NULL CHECK (status IN ('active', 'inactive')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS meals (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack', 'other')),
		eaten_at TEXT NOT NULL,
		calories REAL NOT NULL DEFAULT 0,
		protein_g REAL NOT NULL DEFAULT 0,
		carbs_g REAL NOT NULL DEFAULT 0,
		fat_g REAL NOT NULL DEFAULT 0,
		fiber_g REAL NOT NULL DEFAULT 0,
		sugar_g REAL NOT NULL DEFAULT 0,
		sodium_mg REAL NOT NULL DEFAULT 0,
		notes TEXT,
		source TEXT NOT NULL CHECK (source IN ('manual', 'photo', 'ai', 'import')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE IF NOT EXISTS water (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		amount_ml INTEGER NOT NULL,
		logged_at TEXT NOT NULL,
		source TEXT NOT NULL CHECK (source IN ('manual', 'quick_add', 'import')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE IF NOT EXISTS health_metrics (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		measured_at TEXT NOT NULL,
		height_cm REAL,
		weight_kg REAL,
		bmi REAL,
		bmr REAL,
		tdee REAL,
		body_fat_pct REAL,
		activity_level TEXT,
		goal TEXT CHECK (goal IN ('lose', 'maintain', 'gain')),
		notes TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE IF NOT EXISTS reminders (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		type TEXT NOT NULL CHECK (type IN ('water', 'meal', 'weight', 'custom')),
		title TEXT NOT NULL,
		body TEXT,
		time TEXT NOT NULL,
		days_of_week TEXT,
		timezone TEXT,
		start_date TEXT,
		end_date TEXT,
		enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	);`,
	'CREATE INDEX IF NOT EXISTS idx_meals_user_eaten_at ON meals (user_id, eaten_at);',
	'CREATE INDEX IF NOT EXISTS idx_water_user_logged_at ON water (user_id, logged_at);',
	'CREATE INDEX IF NOT EXISTS idx_health_metrics_user_measured_at ON health_metrics (user_id, measured_at);',
	'CREATE INDEX IF NOT EXISTS idx_reminders_user_enabled ON reminders (user_id, enabled);'
];
